# Generated by Django 3.0.8 on 2020-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=1.0, max_digits=18)),
            ],
        ),
    ]
