# Generated by Django 3.0.8 on 2020-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200719_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2bwallet',
            name='user',
        ),
        migrations.AlterField(
            model_name='b2bwallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18),
        ),
    ]
