# Generated by Django 3.0.8 on 2020-07-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200720_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2btransactions',
            options={'ordering': ('tx_id',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='b2bwallet',
            options={'ordering': ('id',), 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.RenameField(
            model_name='b2btransactions',
            old_name='wallet_id',
            new_name='wallet',
        ),
    ]
