# Generated by Django 3.0.8 on 2020-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200721_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2btransactions',
            options={'ordering': ('-tx_id',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='b2bwallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='b2bwallet',
            name='label',
            field=models.CharField(choices=[('W', 'Withdraw'), ('D', 'Deposit'), ('C', 'Checking'), ('BTC', 'Crypto')], default='D', max_length=15),
        ),
    ]
