# Generated by Django 3.0.8 on 2020-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200723_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2btransactions',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name='b2bwallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=18, default=0.0, max_digits=36),
        ),
        migrations.AlterField(
            model_name='b2bwallet',
            name='label',
            field=models.CharField(choices=[('btc', 'BitCoin'), ('eth', 'Etherium'), ('bat', 'Basic Attention Token'), ('xrp', 'Ripple')], default='D', max_length=15),
        ),
    ]
